[tool.poetry]
name = "pymystiko-cli"
version = "0.3.1"
description = ""
authors = ["Daniel Clayton <dan@azwebmaster.com>"]
packages = [
    {include = "pymystiko_cli"}
]

[tool.poetry.scripts]
mystiko = "pymystiko_cli.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.0"
boto3 = "^1.17.75"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
