[tool.poetry]
name = "StringCompare"
version = "0.1.8"
description = "This package contains functions for comparing strings, finding substrings (the first occurrence of the desired string) "
authors = ["Marsel Muzafarov, Ravil Nurgaliev"]
license = "."

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
stringcompare = "stringcompare:main"
