[tool.poetry]
name = "fileshare"
version = "1.0.0"
description = ""
authors = ["aidan <achaplin3@gatech.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
volapi = "^5.22.0"
requests = "^2.25.1"
tqdm = "^4.61.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
fup = "fileshare.main:upload"
fdl = "fileshare.main:download"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
